# -*- coding: utf-8 -*-
"""MM_226_ASS1_STEEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZsYNDfA6GSUr9xZV5n7GXr_pyF69GYgh
"""

import pandas as pd
import json
import os

# Function to convert Excel file (.xlsx) into CSV files for each sheet
def excel_to_csv(input_excel_file):
    # Load the Excel file
    with pd.ExcelFile(input_excel_file) as xls:
        # Loop through each sheet in the Excel file
        for sheet_name in xls.sheet_names:
            # Read the sheet into a DataFrame
            df = pd.read_excel(xls, sheet_name=sheet_name)
            # Create a safe filename for the CSV file
            csv_file_name = f"{sheet_name.replace(' ', '_')}.csv"
            # Save the DataFrame to a CSV file
            df.to_csv(csv_file_name, index=False)
            print(f"Converted sheet '{sheet_name}' to CSV: {csv_file_name}")

# Function to convert multiple CSV files into a nested JSON structure
def csv_to_json():
    steel_types = {}

    # Loop through all files in the current directory
    for csv_file in os.listdir():
        if csv_file.endswith('.csv'):
            # Parse steel type and category from filename
            parts = csv_file.split('_')
            steel_type = ' '.join(parts[:2])  # Extract steel type (e.g., 'Duplex Steel', 'Ferritic Steel')
            category = ' '.join(parts[2:-1])  # Extract category (e.g., 'Mechanical Properties')

            # Load the CSV file into a DataFrame
            df = pd.read_csv(csv_file)

            # Add data to the nested JSON structure
            if steel_type not in steel_types:
                steel_types[steel_type] = {}

            steel_types[steel_type][category] = df.to_dict(orient='records')

    # Save the nested JSON structure to a file
    with open('steel_data.json', 'w') as f:
        json.dump(steel_types, f, indent=4)

    print("Converted all CSV files to nested JSON: steel_data.json")

# Main function to execute the pipeline
def main():
    # Input Excel file name (replace with your actual file name)
    input_excel_file = "/content/mm226_ass1.xlsx"

    # Step 1: Convert Excel to CSV files
    excel_to_csv(input_excel_file)

    # Step 2: Convert CSV files to JSON
    csv_to_json()

# Run the main function
if __name__ == "__main__":
    main()